### ISSUE TITLE
Postgress ON CONFLICT DO NOTHING is not supported

### ISSUE THREAD

**Issue by Cooke** [charsleysa/node-sql-ts#2]
Would be nice if insert(..).onConflict(...something or nothing...) could generate "ON CONFLICT DO NOTHING" which is valid postgress (https://www.postgresql.org/docs/9.5/sql-insert.html)

Easy workaround is to instead do .add("ON CONFLICT DO NOTHING")

**Comment by charsleysa** [comment]
Hi @Cooke 

Do you mean like this test case (https://github.com/charsleysa/node-sql-ts/blob/master/test/dialects/insert-tests.ts#L879) or something different?

**Comment by Cooke** [comment]
@charsleysa Hi,

yeh without any columns or constraints specified in the rendered SQL. The rendered string should contain exactly "ON CONFLICT DO NOTHING"
