### ISSUE TITLE
CJS support

### ISSUE THREAD

**Issue by Jytesh** [charsleysa/node-sql-ts#8]
Currently this package only support ESM and attempting to require() it from CJS will result in REQUIRE_ESM error, since you are using rollup it would be simple to add an additional cjs build, and provide [cjs and esm entrypoints](https://nodejs.org/api/packages.html#conditional-exports) in package.json and have support for both CJS and ESM, will you be entertaining PRs for the same? ( I am willing to and its dead simple )

**Comment by charsleysa** [comment]
The ecosystem is slowly moving away from CJS with many popular packages dropping CJS support in favor of ESM-only. This package will head in the ESM-only direction as well.
https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77 

In saying that, currently both the latest ^5 and ^6 versions have the same features and ^5 supports CJS so if you have projects that can't use ESM yet you can continue to use ^5.

**Comment by Jytesh** [comment]
Alright thank you

**Comment by charsleysa** [comment]
Revisiting this, I have reintroduced commonjs support starting v7.1.0 targeting es2022.
